name: Upload Python Package

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          # Use OIDC authentication with PyPI
          PYPI_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p $PYPI_TOKEN

  auth:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    outputs:
      token: ${{ steps.auth.outputs.token }}

    steps:
      - name: Authenticate with PyPI using OIDC
        id: auth
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}